name: build

on:
  schedule:
    - cron:  '0 16 * * *' # Runs at 16:00 UTC every day
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  relationships:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Create local changes
      run: |
        bundle
        sudo apt-get install fdupes
        git fetch --unshallow origin
        ruby script.rb "relationships"

    - name: Commit and Push files
      run: |
        git config --local core.ignorecase true
        git config --local user.name "GitHub Action"
        git config --local user.email "github-action@users.noreply.github.com"
        git add .
        echo `git commit -am "Update 'Relationships'"`
        git pull
        git push --force-with-lease

  work:
    # needs: relationships
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Create local changes
      run: |
        bundle
        sudo apt-get install fdupes
        git fetch --unshallow origin
        ruby script.rb "work"

    - name: Commit and Push files
      run: |
        git config --local core.ignorecase true
        git config --local user.name "GitHub Action"
        git config --local user.email "github-action@users.noreply.github.com"
        git add .
        echo `git commit -am "Update 'Work'"`
        git pull
        git push --force-with-lease

  self_knowledge:
    # needs: [relationships, work]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Create local changes
      run: |
        bundle
        sudo apt-get install fdupes
        git fetch --unshallow origin
        ruby script.rb "self_knowledge"

    - name: Commit and Push files
      run: |
        git config --local core.ignorecase true
        git config --local user.name "GitHub Action"
        git config --local user.email "github-action@users.noreply.github.com"
        git add .
        echo `git commit -am "Update 'Self Knowledge'"`
        git pull
        git push --force-with-lease

  sociability:
    # needs: [relationships, work, self_knowledge]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Create local changes
      run: |
        bundle
        sudo apt-get install fdupes
        git fetch --unshallow origin
        ruby script.rb "sociability"

    - name: Commit and Push files
      run: |
        git config --local core.ignorecase true
        git config --local user.name "GitHub Action"
        git config --local user.email "github-action@users.noreply.github.com"
        git add .
        echo `git commit -am "Update 'Sociability'"`
        git pull
        git push --force-with-lease

  calm:
    # needs: [relationships, work, self_knowledge, sociability]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Create local changes
      run: |
        bundle
        sudo apt-get install fdupes
        git fetch --unshallow origin
        ruby script.rb "calm"

    - name: Commit and Push files
      run: |
        git config --local core.ignorecase true
        git config --local user.name "GitHub Action"
        git config --local user.email "github-action@users.noreply.github.com"
        git add .
        echo `git commit -am "Update 'Calm'"`
        git pull
        git push --force-with-lease

  leisure:
    # needs: [relationships, work, self_knowledge, sociability, calm]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'

    - name: Create local changes
      run: |
        bundle
        sudo apt-get install fdupes
        git fetch --unshallow origin
        ruby script.rb "leisure"

    - name: Commit and Push files
      run: |
        git config --local core.ignorecase true
        git config --local user.name "GitHub Action"
        git config --local user.email "github-action@users.noreply.github.com"
        git add .
        echo `git commit -am "Update 'Leisure'"`
        git pull
        git push --force-with-lease
